from pyrobot import BOT
from pyrogram import Filters, Message
from time import sleep

@BOT.on_message(Filters.command("24", ".") & Filters.me)
def twenty_four_h_witze_a_4_min(bot: BOT,  message:Message):
    bot.send_message(message.chat.id, '24 Stunden Witze: Script started...')
    bot.send_message('witzeposten', 'Was macht ein Zombie am Strand? Auf der faulen Haut liegen.')
    sleep(240)
    bot.send_message('witzeposten', 'Was sagt ein Zombie nach dem Geschlechtsverkehr zu seiner Freundin? Lass stecken, ich komme Morgen wieder.')
    sleep(240)
    bot.send_message('witzeposten', 'Was macht ein Zombie, wenn er ein Mädchen sieht, das ihm gefällt? Er wirft ein Auge auf sie.')
    sleep(240)
    bot.send_message('witzeposten', 'Was macht ein Zombie aus einem Arzt? Einen Hot Doc!')
    sleep(240)
    bot.send_message('witzeposten', 'Was macht ein Zombie beim Fußball? Er fault.')
    sleep(240)
    bot.send_message('witzeposten', 'Warum essen Zombies gerne schwangere Frauen? Wegen der Kinderüberraschung und der Extraportion Milch.')
    sleep(240)
    bot.send_message('witzeposten', 'Was steht auf dem Grabstein eines Zombies, der einen schweren Unfall mit einer Gasflasche hatte? R.I.P. = Rest In Pieces')
    sleep(240)
    bot.send_message('witzeposten', 'Wie nennen die Zombies eine Intensiv-Station? Ein All-you-can-Buffet.')
    sleep(240)
    bot.send_message('witzeposten', 'Wieso sind Gefangene sicherer vor Zombies? Freilaufende Menschen schmecken besser.')
    sleep(240)
    bot.send_message('witzeposten', 'Wenn ein Zombie in ein Rehkitz beißt verwandelt dieses sich in ein Zambi.')
    sleep(240)
    bot.send_message('witzeposten', 'Wie nennt man Zombies mit Fernglas? ZOOMbies')
    sleep(240)
    bot.send_message('witzeposten', 'Was sagt ein Zombie bei einem Date? Ich mag Frauen, die etwas im Kopf haben.')
    sleep(240)
    bot.send_message('witzeposten', 'Backup not found: (A)bort, (R)etry, (P)anic?')
    sleep(240)
    bot.send_message('witzeposten', 'Systemfehler: Fehlermeldung nicht gefunden')
    sleep(240)
    bot.send_message('witzeposten', 'Bundesbahn-Error: Anwendung hat leider einige Minuten Verspätung.')
    sleep(240)
    bot.send_message('witzeposten', 'Monty-Python-Error: And now for something completely different...')
    sleep(240)
    bot.send_message('witzeposten', 'Positiver Error: Sie brauchen heute nichts mehr zu arbeiten!')
    sleep(240)
    bot.send_message('witzeposten', 'Kompromiss-Error: Wollen wir noch mal darüber reden?')
    sleep(240)
    bot.send_message('witzeposten', 'Suizid-Error: Hat alles keinen Sinn mehr, ich hänge mich auf!')
    sleep(240)
    bot.send_message('witzeposten', 'Microsoft-Error: Nicht behebbarer Fehler in der Entwicklungsabteilung!')
    sleep(240)
    bot.send_message('witzeposten', 'Bugfix-Error: Es wird Zeit für ein neues Update Ihrer Software!')
    sleep(240)
    bot.send_message('witzeposten', 'Design-Error: Too much efficient code!')
    sleep(240)
    bot.send_message('witzeposten', 'Zwischenfrage: Heute schon gecrasht?')
    sleep(240)
    bot.send_message('witzeposten', 'Krimineller Error: Sie haben das Recht, die Eingabe zu verweigern. Alles, was Sie hier eingeben, kann in einer späteren Windows-Sitzung gegen Sie verwendet werden!')
    sleep(240)
    bot.send_message('witzeposten', 'Friedlicher Error: Stell Dir vor, Windows stürzt ab, und keiner sieht hin...')
    sleep(240)
    bot.send_message('witzeposten', 'Frank-Schilling-Error: Erst mal gemütlich ein Pils trinken.')
    sleep(240)
    bot.send_message('witzeposten', 'Ein junger Mann voller Träume: Er möchte Schriftsteller werden, er möchte Emotionen wecken, die Leute zum Weinen bringen. Was ist aus ihm geworden? Er schreibt die Fehlermeldungen bei Microsoft Windows...')
    sleep(240)
    bot.send_message('witzeposten', 'Windows ist heute noch nicht abgestürzt. Absturz in 10 Sekunden.')
    sleep(240)
    bot.send_message('witzeposten', 'Bei einer Windows-Aktualisierung kam am Ende folgende Meldung: "Es wurden 17 Dateien GEDOWNLOADET, Ihr System wurde GEUPDATET"! Da hats mir fast die Fußnägel hochgerollt. Irgendwer bei Microsoft-Deutschland (der vermutlich studiert hat und das fünffache von meinem Gehalt kriegt) muß doch sowas lesen und freigeben. Kein Wunder, daß die deutsche Sprachkultur längst auf dem untersten Niveau angekommen ist. Ein kleiner Tip an die Microsoft-Deutschland-Fuzzies. "Es wurden X Dateien HERUNTERGELADEN, Ihr System wurde AKTUALISIERT" wäre kürzer und liest sich gleich viel angenehmer.')
    sleep(240)
    bot.send_message('witzeposten', 'Das war ein schöner Sommer letztes Jahr. Er fiel auf einen Mittwoch.')
    sleep(240)
    bot.send_message('witzeposten', 'Anruf beim Wetteramt: "Ihre leichte Bewölkung wird gerade von der Feuerwehr aus meinem Keller gepumpt!"')
    sleep(240)
    bot.send_message('witzeposten', 'Der für das Sommer-Wetter zuständige Computer wurde von einem Trojaner befallen: dem sogenannten "Regenwurm".')
    sleep(240)
    bot.send_message('witzeposten', 'Metrologen müssten eigentlich Metrolügen heißen.')
    sleep(240)
    bot.send_message('witzeposten', '"Hab gelesen, morgen sollen es 17 Grad werden ... mir ist vor Freude fast der Glühwein aus der Hand gefallen"')
    sleep(240)
    bot.send_message('witzeposten', 'Wetter-Witz über die vier Jahreszeiten: Frühling, Fehler, Herbst und Winter.')
    sleep(240)
    bot.send_message('witzeposten', 'Dieser Sommer ist eine Marketing-Aktion von Jack Wolfskin.')
    sleep(240)
    bot.send_message('witzeposten', 'Wie nennt man den Tag nach zwei Regentagen? Montag!')
    sleep(240)
    bot.send_message('witzeposten', 'Letzten Vatertag hatten wir richtig tolles Wetter: Der Himmel und ich waren den ganzen Tag blau.')
    sleep(240)
    bot.send_message('witzeposten', 'Seit vielen Jahrzehnten erklären alle Eltern ihren Kindern: "Esst eure Teller leer, dann wird schönes Wetter!" Und was haben wir jetzt davon? Fette Kinder und eine Klimaerwärmung!')
    sleep(240)
    bot.send_message('witzeposten', 'Der Sommer ist so mies, dass sich sogar die Sonne verdrückt.')
    sleep(240)
    bot.send_message('witzeposten', 'Zitat zum Thema Wetter: Erfolglose Wahrsager können sich immer noch als Meteorologen bewerben!')
    sleep(240)
    bot.send_message('witzeposten', 'So zickig wie das Wetter derzeit ist, wird es nicht von Petrus, sondern von Petra gemacht.')
    sleep(240)
    bot.send_message('witzeposten', 'Woran erkennt man, dass Sommer wird? Der Regen wird wärmer.')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Nullen laufen im Hochsommer durchs Schwimmbad und treffen auf eine Acht. Sagt die eine Null zur anderen: "Wow, bei der Hitze mit Gürtel!"')
    sleep(240)
    bot.send_message('witzeposten', 'Warnhinweis auf dem Produkt "Deutscher Sommer": „Kann Spuren von Sonne enthalten“.')
    sleep(240)
    bot.send_message('witzeposten', 'Es regnet in Strömen. Der Fußballplatz ist total überschwemmt. Trotzdem soll das Spiel stattfinden. Vor dem Anpfiff fragt der Kapitän seine Mannschaft: "Wollen wir erst mit der Strömung spielen oder dagegen?"')
    sleep(240)
    bot.send_message('witzeposten', '"Den Wettervorhersagen traue ich nie, die stimmen ja doch nicht!" "Naja, die Vorhersagen sind immer korrekt, nur mit dem Datum tun sich die Meteorologen noch etwas schwer."')
    sleep(240)
    bot.send_message('witzeposten', 'Telefonieren zwei Informatiker: "Wie ist das Wetter bei dir?" - "Caps Lock." "Was?" "Shift ohne Ende!"')
    sleep(240)
    bot.send_message('witzeposten', 'Was mich an diesem Sommer stört ist weniger das Wetter, als vielmehr die Angst, dass jeden Moment Last Christmas im Radio läuft.')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Bauern sitzen bei Hochwasser auf dem Dach der Scheune. Sie schauen auf das Wasser und sehen, wie eine Mütze vorbeischwimmt. Da sagt der eine: "Der Besitzer ist bestimmt ertrunken." "Nee", sagt der andere, "das ist Karl, der mäht bei jedem Wetter!"')
    sleep(240)
    bot.send_message('witzeposten', 'Jetzt kann kommen was will: Ich habe mir einen Rollkragenbikini und gefütterte Flip Flops bestellt.')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Indianer gehen zum Medizinmann und fragen ihn wie der Winter wird. Der wirft einen Stein in die Luft und sagt: "Es wird ein kalter Winter. Geht in den Wald und sammelt viel Holz." Am nächsten Tag kommen immer wieder einige Indianer und fragen ihn, wie der Winter wird. Er wirft jedes Mail einen Stein in die Luft und sagt: "Es wird ein kalter Winter. Geht in den Wald und sammelt viel Holz." Schließlich überlegt er sich, ob das auch stimmt, was er da erzählt. Er ruft beim Wetteramt an und fragt nach wie der Winter wird. Dort bekommt er zur Antwort: "Es wird ein kalter Winter. Die Indianer sammeln Holz wie die Verrückten."')
    sleep(240)
    bot.send_message('witzeposten', 'Die kleine Anna weckt ihren Vater. "Nun Anna, was haben wir denn für ein Wetter?" - "Weiß ich nicht. Man kann es vor lauter Nebel nicht sehen!"')
    sleep(240)
    bot.send_message('witzeposten', '„Dieser Frühling wurde im Körper eines Herbstes geboren.“')
    sleep(240)
    bot.send_message('witzeposten', 'Auch ein Schirmherr kann nass werden.')
    sleep(240)
    bot.send_message('witzeposten', 'Alte Volksweisheit zum Wetter: Bleibt der Juli warm und heiß, am liebsten ich im Freien scheiß.')
    sleep(240)
    bot.send_message('witzeposten', 'Was haben Männer und das Wetter gemeinsam? Es ist unmöglich, sie zu ändern.')
    sleep(240)
    bot.send_message('witzeposten', 'Witziges Zitat: „Ich freue mich wenn es regnet, denn wenn ich mich nicht freue, regnet es auch!“')
    sleep(240)
    bot.send_message('witzeposten', 'Alle reden vom Wetter und der Sommer sagt "April, April".')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Gefangener wird vom Pfarrer zum Galgen begleitet. Es regnet in Strömen, der Pfarrer hält den Schirm. Sagt der Gefangene: "So ein Sauwetter, Herr Pfarrer." Pfarrer: "Sie haben es gut, Sie müssen nur hin - ich muss auch wieder zurück."')
    sleep(240)
    bot.send_message('witzeposten', 'Summer is not found in your country. Please try Spain.')
    sleep(240)
    bot.send_message('witzeposten', 'Sommer ist in deinem Land leider nicht verfügbar.')
    sleep(240)
    bot.send_message('witzeposten', 'Wetter-Durchsage: Der kleine November möchte bitte aus dem Mai abgeholt werden!')
    sleep(240)
    bot.send_message('witzeposten', 'Fragt ein Passant einen anderen: "Entschuldigen Sie! Wenn ich diesen Weg nehme, komme ich dann zum Wetteramt?" - "Voraussichtlich!"')
    sleep(240)
    bot.send_message('witzeposten', 'Der Frühling ist wie ein Makler: Zeigt dir kurz, wie nett es sein könnte und nervt dann nur noch.')
    sleep(240)
    bot.send_message('witzeposten', 'Und der Preis für den besten Schauspieler geht an...Frühling für seine Rolle als Winter.')
    sleep(240)
    bot.send_message('witzeposten', 'Sagt der Mond zur Sonne: "Mensch hast Du ein Glück, morgen schon wieder frei!"')
    sleep(240)
    bot.send_message('witzeposten', 'Treffen sich zwei Spatzen. Fragt der eine: "Was wollen wir heute unternehmen?" Darauf der andere: "Lass uns zum Tegernsee fliegen." - "Wo treffen wir uns?" - "Auf der großen Eiche am Jachtclub." - "Flieg du schon mal voraus, ich habe noch was zu erledigen." Der erste Spatz wartet am verabredeten Platz und erst nach drei Stunden, trifft sein Freund ein. "Wo warst du denn so lange?" - "Ach", antwortet sein Freund, "ich dachte, bei dem schönen Wetter gehe ich zu Fuß."')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist die gefährlichste Zeit des Jahres? Der Sommer: Die Sonne sticht, die Salatköpfe schießen, die Bäume schlagen aus und der Rasen wird gesprengt.')
    sleep(240)
    bot.send_message('witzeposten', 'Der empörte Ehemann: "Bei diesem Sauwetter soll ich einkaufen gehen? Da jagt man ja keinen Hund auf die Straße!" Erwidert seine Frau ungeniert: "Ich habe ja auch nicht gesagt, dass du den Hund mitnehmen sollst!"')
    sleep(240)
    bot.send_message('witzeposten', 'Wegen des großen Erfolgs in hellgrau gibt es den Frühling nun auch in dunkelgrau.')
    sleep(240)
    bot.send_message('witzeposten', 'Später nach dem Sport muss ich nicht in die Dusche. Ich stelle mich einfach auf die Wiese.')
    sleep(240)
    bot.send_message('witzeposten', 'Wettervorhersage an der Nordsee. Wenn du das Meer sehen kannst, wird es bald regnen. Wenn du das Meer nicht sehen kannst, regnet es bereits.')
    sleep(240)
    bot.send_message('witzeposten', 'Alle machen Witze übers Wetter, aber keiner nimmts mit Humor?')
    sleep(240)
    bot.send_message('witzeposten', 'Sagt ein Schneemann zum anderen: "Du schuldest mir noch 100 Euro!" Darauf antwortet der andere: "Warte noch bis Juli, dann bin ich wieder flüssig!"')
    sleep(240)
    bot.send_message('witzeposten', 'Was haben Wolken und Frauen gemeinsam? Wenn sie sich verziehen, kann es noch ein schöner Tag werden!')
    sleep(240)
    bot.send_message('witzeposten', 'Richtig geschrieben müsste es so sein: Wettervorher-Sage.')
    sleep(240)
    bot.send_message('witzeposten', 'Mut ist, wenn man ohne Regenschirm auf die Straße geht, obwohl der Wetterbericht gutes Wetter angesagt hat.')
    sleep(240)
    bot.send_message('witzeposten', 'Das "Kommando weiße Weihnacht" droht für den 24. Dezember mit Schnee.')
    sleep(240)
    bot.send_message('witzeposten', 'Ansage der Stewardess: “Sehr geehrte Fluggäste, ich begrüße Sie hier in Hamburg, wo das Wetter kalt, scheußlich und ungemütlich ist, genauso wie mein Ex-Mann.”')
    sleep(240)
    bot.send_message('witzeposten', '"Im Laufe des Tages werden örtlich starke Niederschläge auftreten", prophezeit der Meteorologe. Ratlos beugt sich sein Assistent über die Satellitenbilder und Karten "Woraus schließen Sie das?", fragt er. "Ich habe meinen Schirm vergessen und bin zu einer Gartenparty eingeladen."')
    sleep(240)
    bot.send_message('witzeposten', 'Schlechte Wettervorhersagen sind verlässlicher als gute Wettervorhersagen.')
    sleep(240)
    bot.send_message('witzeposten', 'Neulich auf der Baustelle: Der träge Bauleiter zu seinen Leuten: "Seht ihr das Ungeziefer da hinten auf dem Gerüst?" - "Nein, sehr gut, dann machen wir jetzt Feierabend, wegen schlechter Sicht!"')
    sleep(240)
    bot.send_message('witzeposten', '"Du allein bist am miesen Wetter schuld!" – "Warum das denn?" – "Du lügst immer das Blaue vom Himmel herunter!"')
    sleep(240)
    bot.send_message('witzeposten', '"Ach, es ist schrecklich. In meinem Beruf weiß man nie was der nächste Tag bringt." - "Was sind Sie denn von Beruf?" - "Meteorologe."')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Frösche sitzen auf einer Seerose. Plötzlich fängt es an zu regnen. Sagt der eine Frosch zum anderen: "Komm, wir springen ins Wasser, sonst werden wir noch nass."')
    sleep(240)
    bot.send_message('witzeposten', 'Lustige Definition: Was ist Wind? Luft, die es eilig hat.')
    sleep(240)
    bot.send_message('witzeposten', 'Der Klassiker unter den Wetter-Witzen: Sagt der Sohn: "Papi, das Barometer ist gefallen." – "Wie tief denn?" – "Etwa 1,20m."')
    sleep(240)
    bot.send_message('witzeposten', 'Auch bei heißestem Wetter fährt er nur mit geschlossenen Fenstern, damit man glaubt, er hätte eine Klimaanlage.')
    sleep(240)
    bot.send_message('witzeposten', 'Der Frühling scheint in Strömen.')
    sleep(240)
    bot.send_message('witzeposten', 'Das Wetter wird wieder sommerlich! – Super, das heißt, ich kann heute Abend den Fernseher wieder auf den Balkon schieben.')
    sleep(240)
    bot.send_message('witzeposten', 'Das Wetter ist heute wie Recylingpaper. Grau grau grau (Der Witz ist dank der modernen Recyclingtechnologien nicht mehr ganz aktuell).')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Vogelpaar kommt nach Deutschland und hat den ersten Sommer Nachwuchs. Meint die Vogelmutter: "Ich glaube, es wäre sinnvoller, den Kleinen zuerst Schwimmen beizubringen."')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Golfer spielen bei Wind und Regen. Sagt der eine: "Stell dir vor, meine Frau hat mich doch tatsächlich gefragt, ob ich ihr nicht mit im Garten helfen könnte?" Sagt der andere: "Bei dem Sauwetter!"')
    sleep(240)
    bot.send_message('witzeposten', 'Eine Fußballmannschaft Im Flugzeug. Aus Langeweile beginnen die Fußballer in der Maschine mit dem Leder zu spielen. Der Pilot kann die Maschine kaum noch halten und schickt den Funker nach hinten. Nach zwei Minuten ist absolute Ruhe. "Wie hast du denn das gemacht?" - "Ich habe gesagt: Jungs, es ist schönes Wetter draußen, spielt doch vor der Tür!"')
    sleep(240)
    bot.send_message('witzeposten', 'Fliegen zwei Engel durch den Himmel. Fragt der eine den anderen: "Sag´mal, weißt du eigentlich wie morgen das Wetter wird?" - "Ich glaube wolkig." - "Wunderbar, dann können wir uns endlich mal wieder hinsetzen!"')
    sleep(240)
    bot.send_message('witzeposten', 'Die Deutschen haben 6 Monate Winter und 6 Monate keinen Sommer.')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Schneeflocken unterwegs zur Erde, sagt die eine Schneeflocke: "Schön das es so kalt ist, ich werde auf eine Schneepiste fliegen und viel Spaß verbreiten!" Die andere Schneeflocke: "Ach, wie langweilig! Bin unterwegs nach München Verkehrschaos auf den Straßen verursachen..."')
    sleep(240)
    bot.send_message('witzeposten', 'Das schönste Wetter nützt nichts, wenn es regnet.')
    sleep(240)
    bot.send_message('witzeposten', 'Das Wetter ist meistens draußen.')
    sleep(240)
    bot.send_message('witzeposten', 'Deutschland ist keine Bananenrepublik. Dazu ist das Wetter zu schlecht.')
    sleep(240)
    bot.send_message('witzeposten', 'Wenn der Hahn kräht auf dem Huhn, hat das mit Wetter nix zu tun!')
    sleep(240)
    bot.send_message('witzeposten', 'Immer wenn es blitzt und donnert stehen die Ostfriesen auf ihrem Balkon und schauen freundlich in den Himmel. Warum? Weil sie meinen der Liebe Gott fotografiere sie.')
    sleep(240)
    bot.send_message('witzeposten', 'Der Immobilienmakler erklärt: "Ich will ganz ehrlich zu Ihnen sein. Dieses Haus hat auch einige Nachteile. Im Norden befindet sich eine Mülldeponie, im Osten ist die Kläranlage, im Süden ist eine Stinktierzucht und im Westen liegt die Fischfabrik." "Oh, und welche Vorteile hat dann dieses Haus?" "Nun ja, Sie wissen immer, aus welcher Richtung der Wind kommt...')
    sleep(240)
    bot.send_message('witzeposten', 'Eine alte Bauernregel: Kräht der Hahn heut auf dem Mist, ändert sichs Wetter oders bleibt wie es ist!')
    sleep(240)
    bot.send_message('witzeposten', 'Das Borstenschwein ist ganz empört: Der Sturm hat die Frisur zerstört.')
    sleep(240)
    bot.send_message('witzeposten', '"Wie fanden Sie das Wetter heute?" – "Ganz einfach, ich ging kurz vor die Tür, da war es schon."')
    sleep(240)
    bot.send_message('witzeposten', 'Was sieht man, wenn man bei Regen auf dem Eiffelturm steht? Lauter nasse Pariser.')
    sleep(240)
    bot.send_message('witzeposten', 'Was macht eine Wolke, wenn es juckt? Sie sucht einen Wolkenkratzer.')
    sleep(240)
    bot.send_message('witzeposten', 'Was für ein heißer Tag mit nonstop Sonnenschein. Ich glaube, ich wechsle gleich den Aggregatzustand bei der Hitze.')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist ein Keks unter einem Baum? - Ein schattiges Plätzchen.')
    sleep(240)
    bot.send_message('witzeposten', 'Es ist so heiß, dass ich in die Sauna geh um mich abzukühlen!')
    sleep(240)
    bot.send_message('witzeposten', 'Warum nimmt eine Blondine eine Autotür mit in die Wüste? - Weil sie, wenn es ihr zu heiß wird, das Fenster herunterkurbeln kann.')
    sleep(240)
    bot.send_message('witzeposten', '"Mama, darf ich in diesem Sommer endlich mal einen Bikini tragen?" "Nein, Kevin!"')
    sleep(240)
    bot.send_message('witzeposten', 'Der Kopf tut weh, die Füße stinken - höchste Zeit Bier zu trinken!')
    sleep(240)
    bot.send_message('witzeposten', 'Denkt Euch, ich habe das Christkind gesehen;\nes kam aus der Kneipe, es konnte kaum stehen\n\nEs torkelte durch den Tannenwald\nund hatte den Bauch voller Korn und Alt.\n\nAuf Geschenke braucht Ihr nicht zu hoffen,\ndie hat das Christkind alle versoffen.\n\nAus der Kneipe schmiss der Wirt es hinaus\nmein Gott, wie sah das Christkind nur aus?\n\nDie Haare zerzaust und das Hemdchen war fleckig, \ndarüber ein Mantel, auch ziemlich dreckig.\n\nDie Nase rot-blau, und der Rücken ganz krumm,\nund in der Manteltasche ne Buddel mit Rum.\n\nEin Schluck aus der Pulle aufs Weihnachtsfest,\nder gab dem Christkind endgültig den Rest.\n\nMan hörte es noch Pfosit Neujah lallen,\ndann liess es sich einfach zu Boden fallen.\n\nAuf allen Vieren mußte es kriechen,\nseine Fahne konnte man meterweit riechen.\n\nEin Engel half ihm auf die Beine,\nder war bekifft, Ihr wisst, was ich meine!\n\nDer Engel flog zum Himmel geschwind,\nzurück blieb das volltrunkene Christuskind.\n\nDann, auf einer Lichtung, da hat es mit List,\nFrohe Weihnachten in den Schnee gepisst.\n\nUnd Oh, du fröhliche grölend im Suff,\nwankte es weiter in Richtung Puff.\n\nDort hat es die liebe lange Nacht\nmit Champagner und Nutten zugebracht.\n\nUnd liess sich von einem geilen Hasen\nerstmal das Ave Maria blasen.\n\nDanach, da schlief es dann endlich ein,\nund träumte von einem Fass voller Wein.\n\nGestern hab ich es wieder getroffen,\nund denkt Euch, es war schon wieder besoffen.')
    sleep(240)
    bot.send_message('witzeposten', 'Was wäre, wenn Weihnachten nicht vor über 2000 Jahren, sondern heute stattgefunden hätte? Säugling in Stall gefunden - Polizei und Jugendamt ermitteln. Schreiner aus Nazareth und unmündige Mutter vorläufig festgenommen.')
    sleep(240)
    bot.send_message('witzeposten', 'Vater: "Fritzchen, zünde doch bitte den Christbaum an!" Nach einer Weile fragt Fritzchen: "Vati, die Kerzen auch?"')
    sleep(240)
    bot.send_message('witzeposten', '"Ach, Oma, die Trommel von dir war wirklich mein schönstes Weihnachtsgeschenk bisher." "Tatsächlich?" freut sich Oma. "Ja, Mami gibt mir seit Weihnachten jeden Tag einen Euro, wenn ich aufhöre zu spielen!"')
    sleep(240)
    bot.send_message('witzeposten', '"Ich bin sehr besorgt um meine Frau. Sie ist nämlich bei diesem schlimmen Schneetreiben zum Weihnachtsmarkt gegangen." - "Na, sie wird sich schon in irgendeinem Geschäft unterstellen können, oder?" - "Eben, darum bin ich ja besorgt!"')
    sleep(240)
    bot.send_message('witzeposten', 'Fragt die eine Gans eine andere: "Glaubst du an ein Leben nach Weihnachten?"')
    sleep(240)
    bot.send_message('witzeposten', 'Treffen sich 2 Blondinen, sagt die eine: "Dieses Jahr ist Weihnachten an einem Freitag!" Sagt die andere: "Hoffentlich nicht an einem 13ten!"')
    sleep(240)
    bot.send_message('witzeposten', 'Eltern: Du sollst uns doch nicht anlügen! Kind: Ich soll euch nicht anlügen? Ich sag nur "Weihnachtsmann, Osterhase, Nikolaus".')
    sleep(240)
    bot.send_message('witzeposten', 'Die Großmutter zur Enkelin: "Du darfst Dir zu Weihnachten von mir ein schönes Buch wünschen!" - "Fein, dann wünsche ich mir Dein Sparbuch."')
    sleep(240)
    bot.send_message('witzeposten', 'Am Tag vor Heilig Abend sagt das kleine Mädchen zu seiner Mutter: "Mami, ich wünsche mir zu Weihnachten ein Pony!" Darauf die Mutter: "Na gut, mein Schatz, morgen gehen wir zum Friseur."')
    sleep(240)
    bot.send_message('witzeposten', 'Die schwierigste Aufgabe des Vaters zu Weihnachten: Den Kindern klar machen, dass er der Weihnachtsmann ist, und der Frau klar machen, dass er es nicht ist.')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Frauen treffen sich: "Ich war mit meinem Mann gestern auf dem Weihnachtsmarkt." "Und, bist Du ihn losgeworden?"')
    sleep(240)
    bot.send_message('witzeposten', 'Frage: Welche Nationalität hat der Weihnachtsmann? Antwort: Nordpole.')
    sleep(240)
    bot.send_message('witzeposten', 'Petra schwelgt in Erinnerungen: "Als Kind mochte ich es, im Winter in der Stube vor loderndem Feuer zu sitzen. Leider gefiel das meinem Papa nicht. Er hat es verboten." "Warum denn?" Nun. wir hatten keinen Kamin!')
    sleep(240)
    bot.send_message('witzeposten', 'Unterhaltung kurz nach Weihnachten: "Sag mal, war eigentlich unter deinen Weihnachtsgeschenken auch eine echte Überraschung?" Antwort: "Aber ja! Ich bekam von meinem Chef ein Buch, das ich meinem Kollegen Müller vor Jahren geliehen hatte!"')
    sleep(240)
    bot.send_message('witzeposten', 'Es ist kurz vor Weihnachten, Fritzchen geht zur seiner Mutter und sagt: "Du, Mama du kannst die Eisenbahn vom Wunschzettel streichen, ich habe nämlich zufällig eine im Wandschrank gefunden!"')
    sleep(240)
    bot.send_message('witzeposten', 'Es fragt ein Schotte seine Frau: "Was wünschst du dir dieses Jahr zu Weihnachten?" "Ich weiß nicht", antwortet seine Frau. "Gut, dann schenke ich dir ein weiteres Jahr zum Überlegen."')
    sleep(240)
    bot.send_message('witzeposten', 'Scheinheilig ist, wenn man das ganze Jahr die Pille nimmt und zu Weihnachten singt: "Ihr Kinderlein kommet..."')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Mann fragt seine Frau: "Schatz, was wünschst Du dir denn zu Weihnachten? Die Frau: "Die Scheidung!" Er: "Na, soviel wollte ich eigentlich nicht ausgeben!"')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Vater resümiert: "Ich weiß jetzt, warum Weihnachten in meiner Kindheit so schön war. Ich musste die ganzen Geschenke nicht bezahlen!"')
    sleep(240)
    bot.send_message('witzeposten', 'Scherz mit hörbar sächsischem Hintergrund: "Papa, ich wünsche mir einen Globus zu Weihnachten." "Kommt nicht in Frage, in die Schule fährst du mit dem Schulbus und aufs Klo gehst du zu Hause!"')
    sleep(240)
    bot.send_message('witzeposten', 'Oh Tannenbaum, Oh Tannenbaum, \nder Opa sitzt im Kofferraum. \nDie Oma knallt die Türe zu, \nder Opa schreit; Du blöde Kuh.')
    sleep(240)
    bot.send_message('witzeposten', 'Ostfriesenwitz: Warum klettern die Ostfriesen Anfang Dezember immer durch das Fenster? Weil Weihnachten vor der Tür steht!')
    sleep(240)
    bot.send_message('witzeposten', 'Advent, Advent, ein Lichtlein brennt. Erst eins, dann zwei, dann drei, dann vier, dann steht das Christkind vor der Tür. Und wenn das fünfte Lichtlein brennt, dann hast du Weihnachten verpennt.')
    sleep(240)
    bot.send_message('witzeposten', 'Sie zu ihrem Mann: Es ist schon das siebte Mal, dass meine Schwiegermutter am Weihnachten zu uns kommt. Diesmal lassen wir sie aber rein.')
    sleep(240)
    bot.send_message('witzeposten', 'Nach der Firmen Weihnachtsfeier wacht Peter auf und erinnert sich an einen Streit mit dem Chef. Seine Freundin: "Du hast zu ihm gesagt, dass er ein Depp sei und er hat dich deswegen gefeuert" Peter: "Der kann mich mal" Sie: "Das habe ich auch zu ihm gesagt - Du hast den Job wieder."')
    sleep(240)
    bot.send_message('witzeposten', 'Was macht die Blondine mit zwei Kerzen vor sich vor dem Spiegel? Sie feiert den vierten Advent.')
    sleep(240)
    bot.send_message('witzeposten', 'Blondinenwitz: Drei Blondinen treffen sich nach Weihnachten. "Mein Freund hat mir ein Buch geschenkt.", sagt die eine. "Dabei kann ich doch gar nicht lesen!" - "Das ist doch gar nichts! Mein Freund hat mir einen Terminplaner gekauft, dabei kann ich gar nicht schreiben!" - "Bei mir ist es noch viel schlimmer! Mein Freund hat mir einen Deo Roller gekauft, dabei habe ich doch gar keinen Führerschein!"')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Schotte kommt in eine Postfiliale: "Eine 50-Cent-Briefmarke bitte. Aber machen Sie bitte den Preis ab, es soll ein Weihnachtsgeschenk sein!"')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Blondinen sind im Wald und suchen nach dem passenden Weihnachtsbaum. Nach etwa zwei Stunden sagt die eine: "Komm, nehmen wir doch einfach eine Tanne ohne Weihnachtskugeln."')
    sleep(240)
    bot.send_message('witzeposten', 'Männer haben Weihnachten oft das Problem, dass die Gans nicht auf dem Teller liegt, sondern direkt neben Ihnen sitzt.')
    sleep(240)
    bot.send_message('witzeposten', 'Steht ein kleines Mädchen mit seinem neuen Fahrrad an der Ampel. Da kommt ein Polizist zu Pferd angeritten und fragt: "Na, hast du das Fahrrad vom Christkind bekommen?" Das Mädchen antwortet: "Ja, habe ich!" Darauf der Polizist: "Entschuldige, aber ich muss Dir leider 20 Euro abnehmen. Sag dem Christkind nächstes Jahr, es soll dir ein Fahrrad mit Reflektoren schenken, okay?" Da Fragt das Mädchen: "Haben Sie das Pferd auch vom Christkind bekommen?" Der Polizist überlegt kurz und nickt dann. Darauf das Mädchen: "Na, dann sagen Sie dem Christkind nächstes Jahr, das Arschloch kommt hinten hin und nicht oben drauf!"')
    sleep(240)
    bot.send_message('witzeposten', 'Der Familienvater will seine kleine Tochter zu Weihnachten überraschen. Er leiht sich ein Weihnachtsmannkostüm, zieht es sich im heimlich an, nimmt Sack und Rute und geht in das Wohnzimmer: \n"Von draußen, vom Walde komm ich her."\n"Ich muss euch sagen, es Weihnachtet sehr,"\n"und überall auf den Tannenspitzen,"\n"sah ich die goldenen Lichtlein blitzen."\nDarauf die Tochter zur Mutter: "Mama, ist Papa wieder mal besoffen?"')
    sleep(240)
    bot.send_message('witzeposten', 'An Weihnachten bekommt Fritzchen eine Spielzeugeisenbahn. Er baut sie sofort auf zieht sich eine Mütze an und ruft: "Hamburger Hauptbahnhof, Hamburger Hauptbahnhof - Kleine Arschlöcher links einsteigen, große Arschlöcher rechts einsteigen." Schnell kommt seine Mutter aus der Küche gelaufen: "Das sagt man nicht, Fritzchen. Zur Strafe gehst du jetzt eine Stunde in dein Zimmer!" Nach einer Stunde kommt Fritzchen aus seinem Zimmer zurück, geht an die Eisenbahn und ruft: "Hamburger Hauptbahnhof, Hamburger Hauptbahnhof - Kleine Arschlöcher links einsteigen, große Arschlöcher rechts einsteigen und wegen dem riesen Arschloch aus der Küche haben wir eine Stunde Verspätung."')
    sleep(240)
    bot.send_message('witzeposten', 'Der Gabentisch ist öd und leer, die Kinder gucken blöd umher.\nDa lässt der Vater einen krachen, die Kinder fangen an zu lachen')
    sleep(240)
    bot.send_message('witzeposten', 'Wie kann man einen Ostfriesen ärgern? Man schickt ihn in ein rundes Haus und sagt in der Ecke liegt dein Weihnachtsgeschenk!')
    sleep(240)
    bot.send_message('witzeposten', '"Meine Frau wünscht sich etwas zu Weihnachten, das ihr zu Gesicht steht!"- "Kauf ihr einen Faltenrock!"')
    sleep(240)
    bot.send_message('witzeposten', 'Auf einer Kreuzung stoßen am Heilig Abend zwei Autos zusammen. Ein Polizist kommt und zückt seinen Notizblock. Darauf der eine Fahrer: "Aber Herr Polizist, man wird doch wohl noch auf das Weihnachtsfest anstoßen dürfen!"')
    sleep(240)
    bot.send_message('witzeposten', 'Viagra wird demnächst auch flüssig erhältlich sein. Da bekommt der Begriff "Einen heben gehen" eine ganz neue Bedeutung.')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist eine Viagrette? Die kleine Pille für den Ständer zwischendurch.')
    sleep(240)
    bot.send_message('witzeposten', 'Was passiert wenn ein Glühwürmchen Viagra nimmt? Es wird zu einer Stehlampe!')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Mann geht steif wie ein Pinguin über die Straße und begegnet einem Freund. Fragt der Freund: "Hast Du es an der Wirbelsäule?" "Nein", antwortet der andere, "ich habe eine Viagra-Pille genommen und die ist mir im Hals stecken geblieben."')
    sleep(240)
    bot.send_message('witzeposten', 'Warum werfen die Österreicher die Viagra-Pillen in die Tannenwälder? Ganz einfach - Sie wollen zu Weihnachten Tannenbäume mit Ständer.')
    sleep(240)
    bot.send_message('witzeposten', 'Die Nachfrage nach Viagra ist jetzt zurückgegangen. - Die Frauen schaffen es nicht mehr!')
    sleep(240)
    bot.send_message('witzeposten', 'Was der Kaffee ist fürs Kränzchen, das ist Viagra für das Schwänzchen.')
    sleep(240)
    bot.send_message('witzeposten', 'Wird er im Alter manchmal weich, nimm Viagra dann steht er gleich.')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist Tierquälerei? Einer Schlange Viagra geben.')
    sleep(240)
    bot.send_message('witzeposten', 'Das erste mit Hilfe von Viagra gezeugte Baby ist geboren worden. Es konnte bei der Geburt schon stehen.')
    sleep(240)
    bot.send_message('witzeposten', 'Fragt ein Mann seinen Freund: "Du nimmst doch Viagra, wie ist denn das?" Der Freund: "Absolut stark. Man hat das Gefühl man könnte alles niedermachen. Aber eigentlich ist es für zu Hause viel zu schade!"')
    sleep(240)
    bot.send_message('witzeposten', 'Warum darf man einem 80-jährigen Mann kein Viagra mehr geben? Man kriegt sonst den Sargdeckel nicht zu.')
    sleep(240)
    bot.send_message('witzeposten', 'Meint der Casanova zu einem Freund: "Scheiss Viagra ... früher war ich der King ... heute kann es jeder."')
    sleep(240)
    bot.send_message('witzeposten', 'Was passiert, wenn man Viagra auf dem Rasen verstreut? Man kann die Regenwürmer mit einem Hammer zurückschlagen!')
    sleep(240)
    bot.send_message('witzeposten', 'Was wäre für viele Viagra Patienten wünschenswert? Das mehr Blut in den Kopf geht.')
    sleep(240)
    bot.send_message('witzeposten', 'Das beliebteste Reiseziel 1998 für Blondinen war Kanada! Warum? Wegen der Viagra-Fälle!')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist der Unterschied zwischen einem Mann, der eine Flasche Whisky trinkt, und einem, der eine Packung Viagra schluckt? Der eine hat einen sitzen, dass er nicht mehr stehen kann. Der andere hat einen stehen, dass er nicht mehr sitzen kann.')
    sleep(240)
    bot.send_message('witzeposten', 'In Polen wurde Viagra gesetzlich verboten. Warum? Na ist doch klar: Alles was dort länger als zwei Stunden steht, wird mitgenommen.')
    sleep(240)
    bot.send_message('witzeposten', 'Viagra gibt es jetzt auch als Virus für Computer. Der Virus macht aus der Floppy-Disk eine Festplatte.')
    sleep(240)
    bot.send_message('witzeposten', 'Was sagt der Papst, wenn er eine Viagra genommen hat? - "Heiliges Kanonenrohr!"')
    sleep(240)
    bot.send_message('witzeposten', 'Hast du schon einmal Viagra probiert? "Ja, und ich stehe dazu."')
    sleep(240)
    bot.send_message('witzeposten', 'Ein amerikanischer Architekt rettet ein internationales Baudenkmal: Der Schiefe Turm von Pisa steht wieder senkrecht. Sein Geheimtipp: Viagra ins Grundwasser.')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist Viagra-Oxid? Lattenrost!')
    sleep(240)
    bot.send_message('witzeposten', 'Was hat ein Zöllner mit Viagra? Einen Zollstock!')
    sleep(240)
    bot.send_message('witzeposten', 'Wie heißt der neue Werbespruch von Viagra? "Wir stellen die Weichen!"')
    sleep(240)
    bot.send_message('witzeposten', 'Und wie heißt das Lied von Viagra? "Stand by me."')
    sleep(240)
    bot.send_message('witzeposten', 'Was haben Disney World und Viagra gemeinsam? Man wartet über eine Stunde nur um zwei Minuten Spaß zu haben.')
    sleep(240)
    bot.send_message('witzeposten', 'Verkehrschaos in Holland: Ein Laster mit Viagra ist in einen Kanal gefahren, alle Klappbrücken gingen hoch.')
    sleep(240)
    bot.send_message('witzeposten', 'Wie heißt Viagra auf wienerisch? Würstelstand.')
    sleep(240)
    bot.send_message('witzeposten', 'Was bedeutet: "How do you do viagra?" - "Wie gehts, wie stehts?"')
    sleep(240)
    bot.send_message('witzeposten', 'Wie kommt man schnell zu einer günstigen Standleitung? Man steckt Viagra in die Telefondose.')
    sleep(240)
    bot.send_message('witzeposten', 'Jetzt gibt es Viagra auch von der Behörde. Man kennt schon seit vielen Jahren den Satz: "Ich muss zum Amt, die Stütze holen!"')
    sleep(240)
    bot.send_message('witzeposten', 'Neu: "Viagra Light" - für die kleine Nummer zwischendurch.')
    sleep(240)
    bot.send_message('witzeposten', 'Wie sieht eine Viagra-Pille innen aus? -Keine Ahnung? - Du nimmst also auch immer eine Ganze!')
    sleep(240)
    bot.send_message('witzeposten', '"Mutti, kann ein Mädchen mit 8 schon Kinder bekommen?"\n"Nein mein Kind."\nDie kleine dreht sich um und ruft: "OK Jungs, wir können weitermachen."')
    sleep(240)
    bot.send_message('witzeposten', 'Jede Zigarette verkürzt Dein Leben um 15 Sekunden, jeder Orgasmus verlängert Dein Leben um 1 Sekunde.\nFazit: Bums um Dein Leben')
    sleep(240)
    bot.send_message('witzeposten', 'Maxchen fährt in der Straßenbahn. Eine schwangere Frau steigt an der nächsten Haltestelle ein und findet keinen Sitzplatz mehr. Freundlich überlässt Maxchen ihr seinen eigenen Platz. Darauf sagt die Frau zu ihm: "Du bist aber ein kleiner Gentleman!" In der Schule fragt der Lehrer die Kinder: " Wer weiß, was ein Gentleman ist?" Maxchen meldet sich ganz aufgeregt: "Ein Gentleman ist jemand, der eine schwangere Frau sitzen lässt..."')
    sleep(240)
    bot.send_message('witzeposten', 'Drei Arbeiter auf dem Gerüst in der 6. Etage. "Verdammt, ich muss mal aufs Klo!" - "Kein Problem, wir stellen ein Brett vor und stellen uns hinten drauf." Gesagt, getan. In diesem Moment ertönt die Glocke zur Mittagspause. Die beiden hinteren springen ohne nachzudenken vom Brett und holen ihr Essen heraus. Der Lehrling im zweiten Stock zum Meister: "Können Schwule fliegen?" - "Sehr lustig, wieso?" - "Eben flog hier einer vorbei, hat seinen Schwanz in der Hand und hat geschrien: Wo sind die Ärsche!"')
    sleep(240)
    bot.send_message('witzeposten', 'Der Anwalt liest den Verwandten den letzten Willen eines reichen Verstorbenen vor: "Und an Heinz, dem ich versprach, ihn auch in meinem Testament zu erwähnen, einen herzlichen Gruß: "Hallo, Heinz, alter Knabe!"')
    sleep(240)
    bot.send_message('witzeposten', 'Die alte Dame fragt am Strand den kleinen Max zum Spaß: "Werden hier viele Wracks angeschwemmt?" "Nein, Sie sind das erste"')
    sleep(240)
    bot.send_message('witzeposten', '"Das darf nicht wahr sein, Sie haben die Vase runtergeschmissen! Die war 300 Jahre alt!" "Na, da haben wir ja Glueck gehabt, dass sie nicht neu wahr."')
    sleep(240)
    bot.send_message('witzeposten', 'Eine Kundin: "Ich brauche Äpfel für meinen Mann, sind diese hier mit einem Gift bespritzt?" "Nein, das müssen Sie schon selber machen!"')
    sleep(240)
    bot.send_message('witzeposten', 'Was sagt man zu einem Börsenspekulanten, der viel Geld verloren hat? "Trösten Sie sich, Ihr Geld ist nicht verloren, es gehört nur jemand anderem..."')
    sleep(240)
    bot.send_message('witzeposten', 'Der Zollbeamte beugt sich in das geöffnete Fenster des Wagens und fragt: "Alkohol, Zigaretten?" Der Fahrer winkt ab: "Nein Danke, nur zwei Kaffee bitte!"')
    sleep(240)
    bot.send_message('witzeposten', 'Wieso ist der Osterhase das ärmste Tier der Welt? Er hat seinen Schwanz hinten, muss seine Eier verschenken und darf nur einmal pro Jahr kommen!')
    sleep(240)
    bot.send_message('witzeposten', '"Schreiben Sie mich bitte krank, Herr Doktor." "Was fehlt Ihnen denn?" "Ein paar freie Tage."')
    sleep(240)
    bot.send_message('witzeposten', 'Sie: "Warum laufen Sie eigentlich die ganze Zeit hinter mir her?" Er: "Jetzt, wo Sie sich umdrehen frage ich mich das auch..."')
    sleep(240)
    bot.send_message('witzeposten', 'Kommen zwei Kinder in die Drogerie: "Unser Vati ist gerade in einen Bienenkorb gefallen." "Da braucht ihr sicher eine Salbe..." - "Nee, einen Farbfilm!"')
    sleep(240)
    bot.send_message('witzeposten', 'Unter welcher Rubrik werden Abtreibungen ins Stammbuch eingetragen ? Entfernte Verwandte!')
    sleep(240)
    bot.send_message('witzeposten', 'Er: "Ich wäre neugierig, was du machen würdest, wenn ich dich jetzt küssen würde."\n Sie: "Wenn du wirklich so neugierig wärst, wüsstest du es längst!"')
    sleep(240)
    bot.send_message('witzeposten', 'Und wie sagte noch die Holzwurm-Mami zu den Kleinen: "Husch husch, ins Brettchen..."')
    sleep(240)
    bot.send_message('witzeposten', 'Von wo kommen Hamster ursprünglich? Hamsterdam.')
    sleep(240)
    bot.send_message('witzeposten', 'Eine Schlange sagt zur anderen: "Du sind wir eigentlich Giftig?" Sagt die andere: "Ja, warum?" "Weil ich mir gerade in die Zunge gebissen habe."')
    sleep(240)
    bot.send_message('witzeposten', 'Gegen den Rat ihrer Freunde heiraten eine Ameise und ein Elefant. Wie sie zum ersten mal miteinander schlafen wollen, erleidet der Elefant eine Herzattacke und stirbt. Meint die Ameise: "Son Scheiß. Fünf Minuten Spaß und jetzt darf ich für den Rest meines Lebens ein Grab schaufeln..."')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Fliegen krabbeln über einen Globus. Als sie sich zum dritten mal begegnen, meint die eine zur anderen: "Wie klein die Welt doch ist..."')
    sleep(240)
    bot.send_message('witzeposten', 'Kommt ein Hahn mit einem Straußenei auf seine Hühnerfarm: "Mädels, ich will ja nicht meckern, aber kuckt mal, was die Konkurrenz macht...')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Adler stürzt vom Himmel und verschlingt eine Feldmaus am Stück. Die krabbelt bis zum Ende durch und fragt: "Wie hoch fliegen wir?" Der Adler: "Ungefähr 1000 m" "So hoch? Mach bloß keinen Scheiß..."')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Schwein kommt an einer Steckdose vorbei, schaut rein und sagt: "Arme Sau, haben sie dich eingemauert."')
    sleep(240)
    bot.send_message('witzeposten', '"Oh man, so schlecht wie heute hab ich noch nie gespielt", wettert Müller nach dem verlorenen Match beim Handschlag mit Schmidt. Darauf Schmidt: "Ach, Sie haben schon mal gespielt?"')
    sleep(240)
    bot.send_message('witzeposten', 'Ich habe gestern versucht Spiderman anzurufen, der hatte aber kein Netz.')
    sleep(240)
    bot.send_message('witzeposten', 'Kinder haben Superman Schlafanzüge. Superman hat einen Chuck-Norris-Schlafanzug.')
    sleep(240)
    bot.send_message('witzeposten', 'Du hast mich nie mit Superman im gleichen Raum gesehen, oder? Denk mal drüber nach.')
    sleep(240)
    bot.send_message('witzeposten', 'Ich bin so wütend, Hulk nimmt jetzt Unterricht bei mir.')
    sleep(240)
    bot.send_message('witzeposten', 'Superman und Chuck Norris hatten einmal eine Wette: Wer in einem Kampf verliert muss ab sofort die Unterhosen über der Hose tragen.')
    sleep(240)
    bot.send_message('witzeposten', 'Wenn Bruce Banner wütend ist, wird er zum Hulk. Wenn der Hulk wütend ist, wird er zu Chuck Norris.')
    sleep(240)
    bot.send_message('witzeposten', 'Warum stehen Studenten schon um sechs Uhr auf? Weil um halb sieben der Supermarkt zu macht.')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Student telegrafiert nach Hause: "Wo bleibt das Geld?" Antwort vom Vater: "Hier..."')
    sleep(240)
    bot.send_message('witzeposten', 'Prüfer zum Prüfling: "Mit dem, was sie nicht wissen, können noch zwei andere durchfallen!"')
    sleep(240)
    bot.send_message('witzeposten', 'Professor: "Zeichnen Sie einen waagerechten Strich an die Tafel, verlängern Sie diesen nun über die Wand bis zur Tür und schließen Sie diese leise von außen!..."')
    sleep(240)
    bot.send_message('witzeposten', '„Bald zur dunklen Seite der Macht du kehren wirst!" und da schob Yoda das Brot in den Ofen.')
    sleep(240)
    bot.send_message('witzeposten', 'Was waren die letzten Worte des Padawans? "Meister, natürlich weiß ich, an welcher Seite beim Lichtschwert die Klinge rauskommt!"')
    sleep(240)
    bot.send_message('witzeposten', 'Palpatine schickt einen Wettvorschlag an „Wetten, dass...?“: „Ich wette, ich kann mit einem Republikanischen-Armee-Panzer über 25 Jedi springen.“')
    sleep(240)
    bot.send_message('witzeposten', 'Deine Mutter ist so fett, da macht sogar Jabba Augen.')
    sleep(240)
    bot.send_message('witzeposten', 'Die Macht in mir stärker sie wird. Yoda, nimm die Batterie aus dem Mund!')
    sleep(240)
    bot.send_message('witzeposten', 'Chuck Norris war in allen Star Wars Filmen dabei. Er spielte die Macht.')
    sleep(240)
    bot.send_message('witzeposten', 'Geht ein Sturmtruppler zu Vader und sagt: „Du schwarz“. Sagt Vader: „Ich weiß“.')
    sleep(240)
    bot.send_message('witzeposten', 'Was hat Darth Vader an seinem Sternzerstörer hinten für einen Aufkleber? "Sith Happens".')
    sleep(240)
    bot.send_message('witzeposten', 'Was sucht Luke nach Episode V? Einen Second-Hand-Shop.')
    sleep(240)
    bot.send_message('witzeposten', 'Imperator Palpatine, Darth Vader und Grand Moff Tarkin sitzen in einem Shuttle. Der Shuttle stürzt ab. Wer wird gerettet? Die Republik.')
    sleep(240)
    bot.send_message('witzeposten', 'Was passiert, wenn zwei Mercedes zusammenfahren? Krieg der Sterne.')
    sleep(240)
    bot.send_message('witzeposten', '"Dunkel die andere Seite ist" - "Sei still und iss deinen Toast, Yoda!"')
    sleep(240)
    bot.send_message('witzeposten', 'Filmzitat: C3PO: "Da fällt mir aber ein Stein von der Platine!"')
    sleep(240)
    bot.send_message('witzeposten', 'Ein gruseliges Erkenntnis aus Star Wars: "Wenn du nicht weißt, wer dein Vater ist, könnte jede heiße Schnitte deine Schwester sein."')
    sleep(240)
    bot.send_message('witzeposten', 'Wie viele Sturmtruppler braucht man um eine Glühbirne zu wechseln? Zwei. Einen der sie wechselt und einen der den ersten erschießt und den Ruhm einheimst.')
    sleep(240)
    bot.send_message('witzeposten', 'Die allerletzte Episode von „Star Wars“ soll angeblich „Das Wars“ heißen.')
    sleep(240)
    bot.send_message('witzeposten', '"Die Silvesterraketen, die ich bei dir gekauft habe, funktionieren alle nicht!“. „Merkwürdig, ich habe sie doch alle vorher einmal getestet."')
    sleep(240)
    bot.send_message('witzeposten', '„Mutti, Mutti, ich mag Silvester nicht!“. „Sei ruhig und halte still, damit ich die Rakete anzünden kann.“')
    sleep(240)
    bot.send_message('witzeposten', 'Die Freundin gibt ihrem Freund Raketen für Silvester und sagt: „Die kannst du knallen, damit habe ich kein Problem.“')
    sleep(240)
    bot.send_message('witzeposten', 'Hast du Silvester schon was vor? Ich möchte um Mitternacht einen neuen Kalender aufhängen. Darauf freue ich mich schon das ganze Jahr.')
    sleep(240)
    bot.send_message('witzeposten', 'Silvester - Mit Hilfe von Alkohol, das aktuelle Jahr aus dem Gedächtnis löschen.')
    sleep(240)
    bot.send_message('witzeposten', 'Wo kommt Silvester vor Weihnachten? Im Wörterbuch.')
    sleep(240)
    bot.send_message('witzeposten', 'Deine Mudda is’ so fett, dass sie Silvester in zwei Zeitzonen bestaunen kann.')
    sleep(240)
    bot.send_message('witzeposten', 'Ich brauche keine neuen guten Vorsätze. Die alten sind noch praktisch unangetastet.')
    sleep(240)
    bot.send_message('witzeposten', 'Chuck Norris kann mit einem einzigen Streichholz und einem Stein ein einstündiges Silvesterfeuerwerk machen – unter Wasser.')
    sleep(240)
    bot.send_message('witzeposten', 'Chuck Norris hat keine guten Vorsätze. Er ist der gute Vorsatz anderer.')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist der Unterschied zwischen einem Zahnstocher und einem Schwulen? Es gibt keinen, beide stochern in Speiseresten rum!')
    sleep(240)
    bot.send_message('witzeposten', 'Fragt der Scheidungsanwalt: "Warum ist denn ihre Frau weggelaufen?" "Keine Ahnung, Süßer!"')
    sleep(240)
    bot.send_message('witzeposten', 'Robinson und Freitag sitzen auf ihrer einsamen Insel unter einer Palme. Da sagt Robinson: "Wenn wir irgendwann zurück nach England kommen, müssen wir die Geschichte aber anders erzählen..."')
    sleep(240)
    bot.send_message('witzeposten', 'Was haben ein Papagei und ein Schwuler gemeinsam? Beide haben eine beschissene Stange!')
    sleep(240)
    bot.send_message('witzeposten', 'Wie erkennt man einen schwulen Schneemann? Die Karotte steckt im Arsch.')
    sleep(240)
    bot.send_message('witzeposten', 'Wo liegt ein schwuler Sklave? Unter Jochen.')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Sohn kommt vom Internat nach Hauser und erzählt seinem Vater: "Ich glaube mein Zimmernachbar ist schwul!" "Wie kommst Du darauf?", fragt der Vater. "Er schließt seine Augen, wenn ich ihn küsse!"')
    sleep(240)
    bot.send_message('witzeposten', 'Warum haben Lesben schwule Freunde? Jemand muss doch kochen!')
    sleep(240)
    bot.send_message('witzeposten', 'Was macht ein schwuler Regenwurm im Salat? Er wirft erstmal die Schnecken raus!')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Lesben treffen sich in der Pause. Fragt die eine: "Was hast du heute zum Essen dabei?" "Ne Gurke. Willst du was abhaben?" "Nee nee, lass mal stecken..."')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Schwulen brennt das Haus ab. Sagt der eine zum anderen: "Du Dieter, jetzt müssen wir wieder ganz von hinten beginnen."')
    sleep(240)
    bot.send_message('witzeposten', 'Sitzen drei Schwule in der Badewanne. Was hat der in der Mitte? - Geburtstag!')
    sleep(240)
    bot.send_message('witzeposten', 'Sitzen zwei Schwule in der Badewanne. Der eine Furzt. Sagt der andere: "Unser Kind atmet schon..."')
    sleep(240)
    bot.send_message('witzeposten', 'Wieso kann ein Schwabe eine Speisekarte in jeder Sprache der Welt lesen? Weil er nur die Preise liest.')
    sleep(240)
    bot.send_message('witzeposten', 'Wie fangen schwäbischen Kochrezepte an? Man leihe sich einen Topf...')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist das erste Wort eines neugeborenen Schwabens? Bausparvertrag.')
    sleep(240)
    bot.send_message('witzeposten', 'Rezept für schwäbische Tomatensuppe: roter Teller und heißes Wasser.')
    sleep(240)
    bot.send_message('witzeposten', 'Neulich im Schwabenland: Anpfiff beim Fußballspiel: Der Schiedsrichter wirft die Münze in die Luft. Es gab 14 Verletzte.')
    sleep(240)
    bot.send_message('witzeposten', 'Wann sagt ein Schwabe Guten Tag? Niemals, er kann doch kein Hochdeutsch.')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Schwabe ein Berliner und ein Badener wetten um 100 Euro wer am längsten tauchen kann. Der Schwabe ist ertrunken.')
    sleep(240)
    bot.send_message('witzeposten', 'Was bekommt man im Schwabenland, wenn man eine Schorle bestellt? Ein Glas halb mit Sprudelwasser und halb voll Leitungswasser.')
    sleep(240)
    bot.send_message('witzeposten', 'Was verbindet Baden mit Württemberg? Der Bindestrich.')
    sleep(240)
    bot.send_message('witzeposten', 'Was heißt Orgasmus auf Schwäbisch? Sodele.')
    sleep(240)
    bot.send_message('witzeposten', 'Es schreibt ein Schwäbischer Vater seinem Sohn: ...ich wollte dir noch etwas Geld mitschicken, der Brief war aber leider schon zugeklebt.')
    sleep(240)
    bot.send_message('witzeposten', 'Ein schwäbischer Priester lässt den Korb für die Kollekte rumgehen. Als der Korb wieder zurück zum Priester kommt, ist er leer. Der Priester betet daraufhin am Altar: Lieber Gott, danke, dass wenigstens der Korb zurückgekommen ist."')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist der Unterschied zwischen einem Schwaben und einem Ausländer? Den Ausländer versteht man.')
    sleep(240)
    bot.send_message('witzeposten', 'Was macht ein schwäbischer Dalmatiner an Der Kasse? Er sammelt Punkte.')
    sleep(240)
    bot.send_message('witzeposten', 'Warum schraubt ein Schwabe im Kühlschrank immer die Glühbirne heraus? Weil er sich nicht sicher ist, ob beim Schließen das Licht wirklich ausgeht.')
    sleep(240)
    bot.send_message('witzeposten', 'Warum lassen sich Schwaben nach ihrem Tod nur bis zum Bauch eingraben? Damit sie das Grab selber pflegen können.')
    sleep(240)
    bot.send_message('witzeposten', 'Der Name Handy wurde übrigens von einem Schwaben erfunden. Als er so ein Ding zum ersten Mal sah, fragte er ganz erstaunt: "Hänn die koi Schnur?"')
    sleep(240)
    bot.send_message('witzeposten', 'Schwäbisch ist die natürlichste Art der Verhütung.')
    sleep(240)
    bot.send_message('witzeposten', 'Über Baden lacht die Sonne, über Schwaben die ganze Welt.')
    sleep(240)
    bot.send_message('witzeposten', 'Die Schwaben sind sogar geizig mit dem Loben, ein typischer Spruch: Nix gschwätzt isch globt g’nug.')
    sleep(240)
    bot.send_message('witzeposten', 'Warum fahren die Schwaben immer nach Schweden zum Zahnarzt? Weil es da die Krone für unter einen EURO gibt.')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist ein gut aussehender Mann im Schwabenland? Ein Tourist')
    sleep(240)
    bot.send_message('witzeposten', 'Was sind die vier schwersten Jahre im Leben eines Polizisten? Die erste Klasse.')
    sleep(240)
    bot.send_message('witzeposten', '"Diesen alten Schrotthaufen kann man doch nicht Auto nennen" sagt der Polizist bei einer Verkehrskontrolle zu dem nervösen Fahrer. "Eben! Deshalb hab ich ja auch keinen Führerschein!"')
    sleep(240)
    bot.send_message('witzeposten', 'Was machen Polizeiautos vor der Sonderschule? Sie holen ihre Lehrlinge ab.')
    sleep(240)
    bot.send_message('witzeposten', 'Finden zwei Polizeibeamte eine Leiche vor einem Gymnasium. Fragt der eine den anderen: "Du, wie schreibt man denn Gymnasium?" Der andere überlegt und sagt: "Schleppen wir ihn zur Post!"')
    sleep(240)
    bot.send_message('witzeposten', 'Ein kleiner Junge geht die Straße entlang. Er findet einen Gummiknüppel. Ein paar Meter weiter steht ein Polizist. Der kleine Junge fragt: "Ist das Ihr Gummiknüppel, Herr Polizist?" Der Polizist schaut nach und erwidert: "Ne, meinen hab ich verloren."')
    sleep(240)
    bot.send_message('witzeposten', 'Wie heißt eine Polizistin, die ihre Tage hat? - Red Bull')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist ein Polizist im Gefängnis? Sitting Bull')
    sleep(240)
    bot.send_message('witzeposten', 'Der Zollbeamte stoppt den Brummifahrer: "Was haben Sie geladen?" "Anti-Baby-Pillen." Misstrauisch hebt der Beamte die Plane: "Na hören Sie mal, da sitzen ja lauter Frauen mit dicken Bäuchen drin!" "Ach, hab ich fast vergessen: Heute fahr ich die Reklamationen!"')
    sleep(240)
    bot.send_message('witzeposten', '"Ihre Bremsen sind nicht in Ordnung!" sagt der Polizist zu Herrn Schulze, "das macht 25,- Euro." - "Siehst du", strahlt Schulze seine Frau an, "25,- Euro! Und dein Bruder wollte für die Reparatur 60,- Euro haben!"')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist ein in zwei Teile gerissener Bierdeckel? Ein Puzzle für Polizisten. Und was ist ein ganzer Bierdeckel? Die Vorlage dazu.')
    sleep(240)
    bot.send_message('witzeposten', 'Warum gehen Polizisten oft mit Hund auf Streife? Wenigstens einer soll eine abgeschlossene Ausbildung haben.')
    sleep(240)
    bot.send_message('witzeposten', 'Was sind zwei Polizisten auf einem Motorrad mit einem Hund im Beiwagen? Ein Dumm-Dumm-Geschoss mit Bordmechaniker.')
    sleep(240)
    bot.send_message('witzeposten', 'Anruf bei der Polizei: "Hilfe, in unserem Nonnenkloster gab es eine Vergewaltigung!" - "Ist ja schrecklich, wer wurde denn vergewaltigt?" - "Der Briefträger."')
    sleep(240)
    bot.send_message('witzeposten', 'Ein betrunkener Autofahrer wird von der Polizei angehalten. Der Polizist fragt: "Wie heißen Sie?" - "Perowiszkyowiesky" - "Und wie schreiben Sie sich?" - "S-i-c-h."')
    sleep(240)
    bot.send_message('witzeposten', 'Polizeihauptwachtmeister Müller verwarnt den sündigen Autofahrer: "Ich hoffe, dass ich Sie in Zukunft nicht mehr beim Rasen erwische!" - "Ja. das hoffe ich auch", meint der Autofahrer.')
    sleep(240)
    bot.send_message('witzeposten', 'Anruf bei der Polizei: "In meinem Zimmer tickt eine Bombe." - "Wir kommen - solange wie sie tickt haben Sie nichts zu befürchten!"')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Betrunkener wankt nachts über den Parkplatz und tastet alle Autodächer ab. "Was machen Sie denn da?" fragt ein Passant. "Ich suche meinen Wagen", lallt der Betrunkene. "Ja, aber die Dächer sind doch alle gleich ...?" Der Zecher: "Auf meinem ist ein Blaulicht!')
    sleep(240)
    bot.send_message('witzeposten', '"Elefant entlaufen", notiert der Polizist im Protokoll, dann sieht er den Zoodirektor fragend an: "Besondere Kennzeichen?"')
    sleep(240)
    bot.send_message('witzeposten', '"Baden ist hier verboten!", sagt der Polizist einer jungen Frau. "Warum haben sie das nicht gesagt, bevor ich mich ausgezogen habe?" "Ausziehen ist nicht verboten."')
    sleep(240)
    bot.send_message('witzeposten', 'Wie heißt eigentlich: ... der chinesische Dieb: Lang Fing. ... der chinesische Polizist: Lang Fing Fang. ... der chinesischer Polizeihund: Lang Fing Fang Wau. ... die Hütte des chinesischen Polizeihundes: Lang Fing Fang Wau Bau.')
    sleep(240)
    bot.send_message('witzeposten', 'Polizist: "In Ihrem Zustand heißt die Devise: Hände weg vom Steuer!" Betrunkener Autofahrer: "Was, wenn ich blau bin, soll ich auch noch freihändig fahren?"')
    sleep(240)
    bot.send_message('witzeposten', 'Der Geisterfahrer zum Polizisten: "Was heißt hier falsche Richtung? Sie wissen doch gar nicht wohin ich will!"')
    sleep(240)
    bot.send_message('witzeposten', 'Polizist: "Ihr Autokennzeichen ist völlig verschmutzt, Herr Mair." "Macht doch nichts die Nummer weiß ich auswendig."')
    sleep(240)
    bot.send_message('witzeposten', 'Wo hat ein Polizeihund das Arschloch? - Am andren Ende der Leine!')
    sleep(240)
    bot.send_message('witzeposten', 'Es wurden Polizeibeamte gesucht. Zu einem Vorstellungsgespräch haben sich mehrere beworben und schlussendlich sind noch deren zwei übrig geblieben. Der erste kam zum Kommandanten. Der Kommandant sagt: "Ich habe Ihre Bewerbung geprüft und sie sind in der Endauswahl. Wenn sie jetzt noch drei Fragen richtig beantworten, sind sie engagiert. Also, die erste Frage: Wann war der erste Weltkrieg?" "1914 - 1918". "Richtig, 2. Frage, wer hat die Chinesische Mauer erstellt?" "Der Yan hat angefangen, der Yen hat aufgehört". "Wieder richtig, nun die letzte Frage: Gibt es auf dem Mars Lebewesen?" "Man vermutet es, aber man kann es nicht beweisen" "Sie haben alles richtig beantwortet und sind engagiert". Der Bewerber geht nach draußen, wo der andere Mitbewerber wartet. Der fragt ihn, ob es schwierig gewesen sei. Der 1. Bewerber sagte, nein, du musst nur sagen, 1914 - 1918, der Yan hat angefangen, der Yen hat aufgehört und man vermutet es, kann es aber nicht beweisen. Der 2. Bewerber geht zum Kommandanten. Der erklärt ihm alles und kommt zu den abschließenden Fragen. Der Kommandant stellt die erste Frage: "Wann sind Sie auf die Welt gekommen?" Die Antwort des 2. Bewerbers: "1914 - 1918". Der Kommandant wurde etwas ungläubisch, aber ließ sich nicht viel anmerken. Die 2. Frage des Kommandanten: "Wer ist ihr Vater?". "Der Yan hat angefangen, der Yen hat aufgehört". Der Kommandant entrüstet: "Bin ich eigentlich ein Idiot?" "Man vermutet es, aber man kann es nicht beweisen".')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Rentnerpaare sind mit dem Auto auf der Autobahn und fahren nicht mehr als 81 km/h. Ein Polizist hält das Auto an. Der Opa fragt: "Waren wir zu schnell?" Darauf der Polizist: "Nein, aber warum fahren Sie so langsam?" Opa: "Darf man schneller fahren?" Polizist: "Ich denke 100 km/h kann man ruhig fahren." Opa: "Aber auf dem Schild steht A81." Polizist: "Ja, und? Was meinen Sie?" Opa: "Na, da muss ich doch 81 km/h fahren." Polizist: "Nein, das ist doch nur die Nummer der Autobahn." Opa: "Ach so. Danke für den Hinweis." Der Polizist schaut auf die Rückbank des Autos und sieht zwei steif sitzende Omis mit weit aufgerissenen Augen und unendlich großen Pupillen. Da fragt der Polizist fürsorglich die beiden Rentner: "Was ist denn mit den zwei hinten los? Ist den Damen nicht gut?" Da sagt der andere Opa: "Doch, doch. Wir kommen nur von der B252."')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Polizist stoppt einen Autofahrer: "Herzlichen Glückwunsch, sie sind der hunderttausendste Autofahrer auf dieser Strasse und haben 10000,- Euro gewonnen. Wissen sie schon, was sie mit dem Geld anstellen werden?" Der Fahrer antwortet nach nicht langem Überlegen: "Ja, als erstes werde ich meinen Führerschein machen!" Dann die Frau auf dem Beifahrersitz: "Glauben sie ihm kein Wort, Herr Polizist, er ist stockbesoffen!" Darauf der taube Opa auf dem Hintersitz: "Ich wusste gleich, dass wir mit dem geklauten Auto nicht weit kommen!" Auf einmal eine Stimme aus dem Kofferraum: "Sind wir schon über die Grenze?"')
    sleep(240)
    bot.send_message('witzeposten', '"Wenn die Lampe nicht brennt, müssen Sie Ihr Fahrrad schieben", sagt streng der Polizeibeamte. Sagt der Mann: "Das hab ich schon probiert, aber die Lampe brennt trotzdem nicht."')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Mann im Wasser brüllt aus Leibeskräften: "Hilfe, Hilfe! Ich kann nicht schwimmen!" Kommt ein Polizist vorbei und ruft: "Ich kann auch nicht schwimmen, aber mache ich deswegen einen solchen Lärm?"')
    sleep(240)
    bot.send_message('witzeposten', 'Ein Polizist stoppt einen sehr rasanten Autofahrer: "Darf ich bitte Ihren Führerschein sehen?", fragt er höflich. "Wieso Führerschein?", fragt der Autofahrer, "ich denke, den bekommt man erst mit 18!"')
    sleep(240)
    bot.send_message('witzeposten', 'Früher waren die Uniformen bei der Polizei Orange und weiß. Orange für die Oberen und weiß für die Unteren. Und für jede dumme Antwort hat es dann einen kleinen grünen Punkt gegeben.')
    sleep(240)
    bot.send_message('witzeposten', '"Mein Bruder ist bei der Polizei!" - "Meiner auch! Vorgestern haben sie ihn geschnappt!"')
    sleep(240)
    bot.send_message('witzeposten', 'Polizisten sind wie Schnittlauch - innen hohl und treten immer gebündelt auf.')
    sleep(240)
    bot.send_message('witzeposten', 'Wenn die Polizei zu mir sagt "Papiere!", dann sag ich "Schere!" und hab gewonnen.')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Passanten füttern Tauben. Sagt der eine: "Tauben sind wie Politiker." "Wieso?" fragt der andere. Antwort: "Solange sie unten sind, fressen sie einem aus der Hand. Aber sobald sie oben sind, bescheissen sie uns!"')
    sleep(240)
    bot.send_message('witzeposten', 'Der Kanzler Gerhard Schröder will einen arbeitslosen Architekten trösten: "Wenn ich nicht Kanzler wäre, dann würde ich auch Häuser bauen." Darauf der Architekt: "Wenn Sie nicht Kanzler wären, würde ich das auch!"')
    sleep(240)
    bot.send_message('witzeposten', 'Wie schafft man es unter der Regierung Schröder an ein kleines Vermögen zu kommen? Man muss vorher ein großes gehabt haben!')
    sleep(240)
    bot.send_message('witzeposten', 'Gestern war Stromausfall in Berlin. Gerhard Schröder steckte eine Stunde im Fahrstuhl fest. Helmut Kohl stand eine Stunde auf der Rolltreppe...')
    sleep(240)
    bot.send_message('witzeposten', 'Bundeskanzler Schröder soll entführt worden sein. Die Täter verlangen eine Million Mark, andernfalls lassen sie ihn frei.')
    sleep(240)
    bot.send_message('witzeposten', 'Es genügt nicht, unfähig zu sein - Man muß auch in die Politik gehen!')
    sleep(240)
    bot.send_message('witzeposten', 'Parlamentswahlen sind der freie Wettbewerb der Versprechungen!')
    sleep(240)
    bot.send_message('witzeposten', 'Unterhalten sich zwei Männer beim Stammtisch. Fragt der eine: "Kannst Du mir den Unterschied zwischen Kapitalismus und Sozialismus erklären?" Antwort: "Kapitalismus ist die Ausbeutung des Menschen durch den Menschen. Beim Sozialismus ist es genau umgekehrt."')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei Politiker streiten sich während einer Fernsehsendung. Sagt der eine: "Es mag wohl viele Arten geben, Geld zu verdienen, aber nur eine ehrliche!" Fragt der andere: "Und welche soll das sein?" Darauf die direkte Antwort: "Hätte ich mir denken können, dass Sie die nicht kennen."')
    sleep(240)
    bot.send_message('witzeposten', 'Unterhalten sich zwei Wähler. Sagt der eine: "Kennst Du schon den Witz, wo Gerhard Schröder mit einem Strick allein in den Wald geht?" Darauf der andere: "Nein, fängt aber gut an..."')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist der Unterschied zwischen Aids und Linux? Aids ist verbreitet!')
    sleep(240)
    bot.send_message('witzeposten', 'Warum kann man einen C64 schwer unter Linux emulieren? Der C64 hatte Sound!')
    sleep(240)
    bot.send_message('witzeposten', 'Warum will Michael Schumacher nicht für Linux Werbung machen? Schuhmacher steht für Geschwindigkeit und Zukunft.')
    sleep(240)
    bot.send_message('witzeposten', 'Warum kommen alle Linux-Benutzer in den Himmel? Ihr Betriebssystem war Hölle genug!')
    sleep(240)
    bot.send_message('witzeposten', 'Mach das Fenster zu! ... Dem Pinguin wird kalt!')
    sleep(240)
    bot.send_message('witzeposten', 'Warum ist Linux so stabil? Keine Software - keine Abstürze!')
    sleep(240)
    bot.send_message('witzeposten', 'Linux ist wie ein guter Fußballspieler. Erfahren, trotzdem schnell, technisch ausgereift, flexibel. Aber heult beim kleinsten Problem rum.')
    sleep(240)
    bot.send_message('witzeposten', 'Linux wird niemals das am meisten installierte Betriebssystem sein! So oft wie Windows neu installiert werden muss...')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie chillig du bist, Friedrich war Schiller.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie still du bist, die Sportfreunde sind stiller.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie neu du bist, Manuel ist Neuer.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie kalt es draußen ist, Leonardo fährt di Caprio.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie gut es dir geht, Bill Gates besser.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal was du machst, Karl Marx.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie anpassungsfähig du bist, Thomas ist anders.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie viel Geld du Ursula auch schuldest, du kannst dir immer was Von der Leyen.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie cool du bist, Coca ist Cola.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie viel er trainiert, Philipp bleibt Lahm.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie oft du frei hast, Nutten haben Freier.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie gut du auch schläfst, Albert schläft wie Einstein.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie deutsch du bist, Drafi ist Deutscher.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie dicht du bist, Göthe war Dichter.')
    sleep(240)
    bot.send_message('witzeposten', 'Egal wie voll du bist, Rudi ist Völler.')
    sleep(240)
    bot.send_message('witzeposten', 'Bei welchem Schild ist das Wenden auf der Autobahn erlaubt? \nWillkommen im Saarland!')
    sleep(240)
    bot.send_message('witzeposten', 'Was ist eine Blondine zwischen zwei Saarländern?nNicht die Dümmste…')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei saarländische Männer stehen auf einer Brücke und streiten sich. Sagt der eine Saarländer zum Anderen: „Das doo is die Mosel“. Sagt der Andere: „Nä, das do is die Saar“. Daraufhin antwortet der erste Saarländer: „Kumm, ma springe runner, dann wisse mas!“ und springt von der Brücke. Nach etwa einer halben Stunde kommt der gesprungene Saarländer ganz erschöpft auf der Brücke wieder an und sagt: „Ma hotte beide nit Recht. ’s war die A1.“')
    sleep(240)
    bot.send_message('witzeposten', 'Warum können saarländische Kinder kein Versteck spielen?\nWeil keiner nach ihnen sucht.')
    sleep(240)
    bot.send_message('witzeposten', 'Mitten in der Nacht klingelt in Neunkirchen an der Saar das Telefon. Frau Becker geht ran und der Anrufer entgegnet: „Tschuldigung, awwa hann Sie die Numma: Äns, äns, äns?“ Frau Becker antwortet: „Nä, hamma net, mir hann die numma hunnertelf.“ Daraufhin entschuldigt sicher der saarländische Anrufer: „O dann hann ich misch wohl verwählt, das dut ma dann läd, dass isch se gesteert hann.“ Daraufhin Frau Becker: „is net so tragisch, hann jo eh uffstehn misse, weil es Telefon hat gerappelt.“')
    sleep(240)
    bot.send_message('witzeposten', 'Wie erhitzen die Saarländer Milch? Sie zünden die Kühe an.')
    sleep(240)
    bot.send_message('witzeposten', 'Was tut eine Saarländerin, die sich hässlich findet? Sie wirft den Spiegel weg. Was macht ihr Mann, der den Spiegel im Mülleimer findet? Er erschrickt sich und ruft die Polizei.')
    sleep(240)
    bot.send_message('witzeposten', 'Was sagt der saarländische Sekretär auf die Frage seines Chefs, was für diese Woche im Terminkalender steht? „Montag, Dienstag, Mittwoch…“')
    sleep(240)
    bot.send_message('witzeposten', 'Warum bauen die Saarländer runde Häuser? Damit die Hunde nicht an die Ecken pinkeln.')
    sleep(240)
    bot.send_message('witzeposten', 'Zwei pfälzer sitzen in einem Zugabteil, als der Zug plötzlich aus den Gleisen springt. Der Zug also runter von den Gleisen, den Berg hinab, um einen Apfelbaum rum, den Berg wieder raus und wieder rauf auf die Gleise. Da fragt der eine den anderen: "Warum sind wir denn grade runter von den Gleisen, den Berg hinab, um einen Apfelbaum rum, den Berg wieder rauf und wieder rauf auf die Gleise?" Der andere weiß die antwort nicht, meint aber: "Fragen wir den Schaffner." Sie gehen los, und als sie den Schaffner treffen fragen sie diesen: "Warum sind wir denn grade runter von den Gleisen, den Berg hinab, um den Apfelbaum rum, den Berg wieder hinauf und wieder auf die Gleise?" Der Schaffner weiß auch keine Antwort, meint aber: "Lassen sie uns den Lokführer fragen." Die drei gehen zur Lok, der Lokführer öffnet und die drei fragen: "Warum sind wir denn grade runter von den Gleisen, den Berg hinab, umd den Apfelbaum rum, den Berg wieder rauf und wieder auf die Gleise?" Sagt der Lokführer: "Da stand ein Saarländer auf den Gleisen." Da meint einer der beiden Passagiere: " Na und, einfach überfahren!" Darauf der Lokführer: "Habe ich ja versucht, aber da is der Saarländer runter von den Gleisen, den Berg hinab, um den Apfelbaum rum, den Berg wieder rauf und wieder auf die Gleise..."')
    bot.send_message(message.chat.id, '24 Stunden Witze: Script finished!')
